version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - cs3219-peerprep-network
  execution-service:
    build: ./backend/execution-service
    ports:
      - "8000:8000"
    volumes:
      - ./backend/execution-service:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - cs3219-peerprep-network
networks:
  cs3219-peerprep-network:
    driver: bridge

volumes:
  mongodb_data: {}