version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cs3219-peerprep-network
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - cs3219-peerprep-network
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports: ['2181:2181']
    networks: 
      - cs3219-peerprep-network

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks: 
      - cs3219-peerprep-network

  matching-service:
    build:
      context: ./backend/matching-service
      dockerfile: Dockerfile.matching
    container_name: matching-service
    restart: always
    ports:
      - '8002:8002'
    env_file:
      - ./backend/matching-service/.env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - QUESTION_SERVICE_URL=http://question-service:8003
      - COLLABORATION_SERVICE_URL=http://collaboration-service:8004
      - DB_REQUIRE_AUTH=true
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DATABASE_NAME=peerprepMatchingServiceDB
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - KAFKA_BROKERS=kafka:9092
      - DEBUG_MODE=true
      - DEBUG_MATCHING=false
    depends_on:
      - redis
      - mongodb
      - collaboration-service
      - question-service
      - kafka
    networks:
      - cs3219-peerprep-network
  user-service:
    build: 
      context: ./backend/user-service
      dockerfile: Dockerfile.user
    container_name: user-service
    ports:
      - "8001:8001"
    env_file:
      - ./backend/user-service/.env
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/peerprepUserDB?authSource=admin
      WEB_BASE_URL: http://localhost:3000
      API_BASE_URL: http://localhost:8001
      PORT: 8001
      EMAIL_USER: peerprep.team@gmail.com
    networks:
      - cs3219-peerprep-network

  collaboration-service:
    build:
      context: ./backend/collaboration-service
      dockerfile: Dockerfile.collaboration
    container_name: collaboration-service
    restart: always
    ports:
      - '8004:8004'
      - '8005:8005'
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/peerprepCollabServiceDB?authSource=admin
      - HTTP_PORT=8004
      - WS_PORT=8005
      - ROOM_TIMEOUT_MINUTES=10
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - mongodb
      - kafka
    networks:
      - cs3219-peerprep-network

  question-service:
    build:
      context: ./backend/question-service
      dockerfile: Dockerfile.question
    container_name: question-service
    restart: always
    ports:
      - '8003:8003'
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/peerprepQuestionServiceDB?authSource=admin
      - PORT=8003
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - KAFKA_BROKERS=kafka:9092
    depends_on:
      - mongodb
      - kafka
    networks:
      - cs3219-peerprep-network

networks:
  cs3219-peerprep-network:
    driver: bridge

volumes:
  mongodb_data: {}
  redis_data: {}