name: CI (backend - collaboration service)

on:
  pull_request:
    branches: [dev, staging]
    paths:
      - "backend/collaboration-service/**"
      - "pnpm-lock.yaml"
      - "package.json"
      - ".github/workflows/ci-collaboration-service.yml"
  push:
    branches: [dev, staging]
    paths:
      - "backend/collaboration-service/**"
      - "pnpm-lock.yaml"
      - "package.json"
      - ".github/workflows/ci-collaboration-service.yml"

# Cancel older runs on the same PR/branch
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Build
    runs-on: ubuntu-latest
    env:
      CI: true
    services:
      mongodb:
        image: mongo:8
        ports:
          - 27017:27017

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Enable Corepack & pin pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.17.1 --activate
          echo "PATH: $PATH"
          which pnpm
          pnpm -v

      - name: Install deps (workspace root)
        run: pnpm install --frozen-lockfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: backend/collaboration-service
          file: backend/collaboration-service/Dockerfile.collaboration
          push: false
          tags: collaboration-service:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
