name: CI (frontend)

on:
  pull_request:
    branches: [ main, master ]
    paths:
      - "frontend/**"
      - "pnpm-lock.yaml"
      - "package.json"
      - ".github/workflows/ci.yml"
  push:
    branches: [ main, master ]
    paths:
      - "frontend/**"
      - "pnpm-lock.yaml"
      - "package.json"
      - ".github/workflows/ci.yml"

# Cancel older runs on the same PR/branch
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Lint, Typecheck, Build
    runs-on: ubuntu-latest
    env:
      CI: true
      NEXT_TELEMETRY_DISABLED: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Enable Corepack & pin pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.17.1 --activate
          echo "PATH: $PATH"
          which pnpm
          pnpm -v

      - name: Install deps (workspace root)
        run: pnpm install --frozen-lockfile

      # Optional: cache Next.js build cache for faster builds
      - name: Cache Next.js .next/cache
        uses: actions/cache@v4
        with:
          path: frontend/.next/cache
          key: next-cache-${{ runner.os }}-node20-${{ hashFiles('pnpm-lock.yaml', 'frontend/**/*.ts', 'frontend/**/*.tsx', 'frontend/package.json') }}
          restore-keys: |
            next-cache-${{ runner.os }}-node20-

      - name: Lint
        run: pnpm lint
        # Your root scripts are already scoped with --filter frontend

      - name: Typecheck
        run: pnpm typecheck

      - name: Build
        run: pnpm build
