name: Frontend CI

on:
  pull_request:
    branches: [ dev, staging, production ]
    paths:
      - "frontend/**"
      - "pnpm-lock.yaml"
      - "package.json"
      - ".github/workflows/frontend-ci.yml"
  push:
    branches: [ dev, staging, production ]
    paths:
      - "frontend/**"
      - "pnpm-lock.yaml"
      - "package.json"
      - ".github/workflows/frontend-ci.yml"

# Cancel older runs on the same PR/branch
concurrency:
  group: frontend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-build-test:
    name: Frontend Lint, Typecheck & Build
    runs-on: ubuntu-latest
    env:
      CI: true
      NEXT_TELEMETRY_DISABLED: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Enable Corepack & pin pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.17.1 --activate
          echo "PATH: $PATH"
          which pnpm
          pnpm -v

      - name: Install dependencies (workspace root)
        run: pnpm install --frozen-lockfile

      # Cache Next.js build cache for faster frontend builds
      - name: Cache Next.js .next/cache
        uses: actions/cache@v4
        with:
          path: frontend/.next/cache
          key: next-cache-${{ runner.os }}-node20-${{ hashFiles('pnpm-lock.yaml', 'frontend/**/*.ts', 'frontend/**/*.tsx', 'frontend/package.json') }}
          restore-keys: |
            next-cache-${{ runner.os }}-node20-

      - name: Frontend Lint
        run: pnpm lint
        # Root scripts are scoped with --filter frontend

      - name: Frontend Typecheck
        run: pnpm typecheck

      - name: Frontend Build
        run: pnpm build
